### ISSUE TITLE
Create form group component

### ISSUE THREAD

**Issue by ryanolee** [Multiplied-By-One/MBOne-Frontend#14]
Aim:
Make a component that can accept text for a label and a form input as it's child and render in a 1x2 grid like this 
![image](https://user-images.githubusercontent.com/17767073/104644880-3fcea800-56a6-11eb-835c-6d6e848cea6b.png)

Possible usage:
```jsx
<FormGroup label="Test">
     <SomeInputComponent/>
</FormGroup>
```
Details:
* You might be able to leverage something like : https://material-ui.com/components/grid/ to get the layout

**Comment by tsukimi2** [comment]
@ryanolee Is it alright if I have a try at this issue? Thanks.

**Comment by ryanolee** [comment]
Go ahead @tsukimi2 🥇 Don't need to ask for permission 😆 , should assign it to yourself so others know not to pick it up 📈
