### ISSUE TITLE
Create Navbar component

### ISSUE THREAD

**Issue by akinde** [Multiplied-By-One/MBOne-Frontend#29]
![image](https://user-images.githubusercontent.com/22434569/109368634-9d7e1480-784e-11eb-95bd-b8f52f876c2e.png)
![image](https://user-images.githubusercontent.com/22434569/109368581-71629380-784e-11eb-9735-09413b46e4fb.png)
![image](https://user-images.githubusercontent.com/22434569/109368599-83443680-784e-11eb-9ca1-6ed3d3885f62.png)
![image](https://user-images.githubusercontent.com/22434569/109368689-c9999580-784e-11eb-97c0-60888498330b.png)
![image](https://user-images.githubusercontent.com/22434569/109368720-de762900-784e-11eb-8589-21aa04a6b1c7.png)
![image](https://user-images.githubusercontent.com/22434569/109368739-f6e64380-784e-11eb-814e-cdae836c6985.png)

- Takes two lists of components and a string as parameters.
- These parameters consist of the left, center, and right elements of the navbar. 
- The left and right elements are lists of components, evenly spaced horizontally.
- The left element displays components in the list in ascending order (index 0 -> ...)
- The right element displays components in the list in descending order (index # -> 0)
- The center element is a simple header text.

**Comment by tsukimi2** [comment]
@akinde I'll take a try at creating the Navbar.  ^_^

**Comment by tsukimi2** [comment]
@akinde I'm working on the frontend issue Create Navbar component #29 (https://github.com/Multiplied-By-One/MBOne-Frontend/issues/29) and I would like to ask a quick question before submitting a PR of the code I'm working on.  For this issue, one of the requirements said that "The left element displays components in the list in ascending order (index 0 -> ...)".  I would like to ask is there any specific reason why we need to pass a list into the left/right elements of the navbar component? For example, if I construct the navbar as below:

GenericNavbar.js
----------------
``````
...
const GenericNavbar = (props) => {
  const classes = useStyles()

  return (
    <AppBar position="static">
      <Toolbar className={classes.navDisplayFlex}>
        <div className={classes.sideDisplayFlex}>{props.left}</div>
        <div className={classes.centerDisplay}>{props.center}</div>
        <div className={classes.sideDisplayFlex}>{props.right}</div>
      </Toolbar>
    </AppBar>
  );
}
...
``````
and use the navbar component as follow:

    <GenericNavbar
      left={
        <Fragment>
          <ArrowBackIcon />
          <Typography variant="button" display="block" gutterBottom>Create</Typography>
        </Fragment>
      }
      center={"Multiplied By One"}
      right={
        <Fragment>
          <Badge badgeContent={4} color="primary">
            <Typography variant="button" display="block" gutterBottom>Eye Box</Typography>
          </Badge>
          <ArrowRightAltIcon />
        </Fragment>
      }
    />

is this a viable option? Thanks.
