### ISSUE TITLE
Implement sidebar

### ISSUE THREAD

**Issue by ryanolee** [Multiplied-By-One/MBOne-Frontend#42]
![image](https://user-images.githubusercontent.com/17767073/153931932-27d42958-d911-403e-b39a-4098dc52ad08.png)

Acceptance criteria: 
- When the "Burger Icon" is clicked the side bar should toggle between shown and hidden states.
- Use react router to take users to other pages in the app.

**Comment by louisan42** [comment]
PR created in MBO-App repo @ryanolee
